import Head from "next/head";
import { Inter } from "next/font/google";
import Btn from "@/component/Btn";

const inter = Inter({ subsets: ["latin"] });
export default function Home() {
  return (
    <>
      <Head>
        <title>Poke-Library</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
      </Head>
      <main>
        <section className="top-content">
          <div>
            <h1>ポケモン図鑑でパートナーを見つけよう</h1>
            <Btn href={"/monster"} text="Get Start"></Btn>
          </div>
        </section>
      </main>
    </>
  );
}
